name: CVE Scanning for Docker

on:
  schedule:
    - cron: '0 8,18 * * 1-5'
  push:
    paths:
      - 'code/Dockerfile'
      - '.github/workflows/cve-scanning-docker.yml'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: 
docker-practice/actions-setup-docker@321477a1e481dd60b05f9b489cf4b9be467aa15c
      - name: Build
        run: docker build -f Dockerfile -t user/app:latest .
        working-directory: code
      - name: Scan for vulnerabilities
        uses: 
crazy-max/ghaction-container-scan@dfa7e54dc32045120f06d0bc8d7724860f5db0ad
        with:
          image: user/app:latest
